let modelList = [
    { id: 1 , level: 1, children: [], name: '나루토' },
    { id: 2 , level: 1, children: [], name: '사스케' },
    { id: 3 , level: 1, children: [], name: '사이' },
    { id: 4 , level: 1, children: [], name: '사쿠라' },
    { id: 5 , level: 1, children: [], name: '사소리' },
    { id: 6 , level: 1, children: [], name: '암부' },
    { id: 7 , level: 1, children: [], name: '야마토' },
    { id: 8 , level: 1, children: [], name: '카부토' },
    { id: 9 , level: 1, children: [], name: '카린' },

    { id: 10, level: 2, children: [4,4], name: '츠나데' },
    { id: 11, level: 2, children: [5,3], name: '제츠' },
    { id: 12, level: 2, children: [1,7], name: '지라이야' },
    { id: 13, level: 2, children: [8,8], name: '오로치마루' },
    { id: 14, level: 2, children: [6,6], name: '테마리' },
    { id: 15, level: 2, children: [2,2], name: '사스케 주인 1' },
    { id: 16, level: 2, children: [9,9], name: '쥬고' },
    { id: 17, level: 2, children: [], name: '쵸지' },

    { id: 18, level: 3, children: [10,10], name: '카츠유' },
    { id: 19, level: 3, children: [15,8], name: '사스케 주인 2' },
    { id: 20, level: 3, children: [1,1,4], name: '나루토 나선 수리검' },
    { id: 21, level: 3, children: [9,16,2], name: '스이게츠' },
    { id: 22, level: 3, children: [14,17], name: '코테츠' },
    { id: 23, level: 3, children: [3,2,1,4], name: '카카시 암부' },
    { id: 24, level: 3, children: [14,14,6], name: '가아라' },
    { id: 25, level: 3, children: [6,6,3,2], name: '히나타' },
    { id: 26, level: 3, children: [8,14,7], name: '키바' },
    { id: 27, level: 3, children: [17,17], name: '아스마' },
    { id: 28, level: 3, children: [8,7,5,5], name: '시노' },
    { id: 29, level: 3, children: [5,5,9], name: '사소리 히루코' },
    { id: 30, level: 3, children: [13,2,9], name: '만다' },
    { id: 31, level: 3, children: [17,1,15], name: '록 리' },
    { id: 32, level: 3, children: [7,7,23,26], name: '이타치 암부' },
    { id: 33, level: 3, children: [11,11], name: '토비' },
    { id: 34, level: 3, children: [12,12], name: '가마켄' },
    { id: 35, level: 3, children: [4,4,9,8], name: '이노' },
    { id: 36, level: 3, children: [11,1,7], name: '카쿠즈' },
    { id: 37, level: 3, children: [16,13,6], name: '하쿠' },
    { id: 38, level: 3, children: [16,13], name: '키사메' },
    { id: 39, level: 3, children: [17,14,3], name: '칸투로' },

    { id: 40, level: 4, children: [], name: '가아라 반수화'},
    { id: 41, level: 4, children: [], name: '나루토 꼬리 4개해방'},
    { id: 42, level: 4, children: [], name: '휴우가 네지'},
    { id: 43, level: 4, children: [], name: '데이다라'},
    { id: 44, level: 4, children: [], name: '록리 연화'},
    { id: 45, level: 4, children: [], name: '사무이'},
    { id: 46, level: 4, children: [], name: '사소리 완전변형'},
    { id: 47, level: 4, children: [], name: '사스케 2년 후'},
    { id: 48, level: 4, children: [], name: '사이 뿌리닌자'},
    { id: 49, level: 4, children: [], name: '시즈네'},
    { id: 50, level: 4, children: [], name: '야마토 암부'},
    { id: 51, level: 4, children: [], name: '엔마'},
    { id: 52, level: 4, children: [], name: '오로치마루 아카츠키'},
    { id: 53, level: 4, children: [], name: '이타치 아카츠키'},
    { id: 54, level: 4, children: [], name: '자부자'},
    { id: 55, level: 4, children: [], name: '쥬고 주인화'},
    { id: 56, level: 4, children: [], name: '지라이야 호걸'},
    { id: 57, level: 4, children: [], name: '육도 페인 천도'},
    { id: 58, level: 4, children: [], name: '카카시 만화경'},
    { id: 59, level: 4, children: [], name: '카쿠즈 비전인술'},
    { id: 60, level: 4, children: [], name: '칸쿠로 흑비기'},
    { id: 61, level: 4, children: [], name: '쿠레나이'},
    { id: 62, level: 4, children: [], name: '쿠시나'},
    { id: 63, level: 4, children: [], name: '키미마로'},
    { id: 64, level: 4, children: [], name: '킬러비'},
    { id: 65, level: 4, children: [], name: '쵸주로'},
    { id: 66, level: 4, children: [], name: '텐텐'},
    { id: 67, level: 4, children: [], name: '휴우가 히나타 백안'},
    { id: 68, level: 4, children: [], name: '히단 아카츠키'},

    { id: 69, level: 4, children: [], name: ''},
    { id: 70, level: 4, children: [], name: ''},
    { id: 71, level: 4, children: [], name: ''},
    { id: 72, level: 4, children: [], name: ''},
    { id: 73, level: 4, children: [], name: ''},
    { id: 74, level: 4, children: [], name: ''},
    { id: 75, level: 4, children: [], name: ''},
    { id: 76, level: 4, children: [], name: ''},
    { id: 77, level: 4, children: [], name: ''},
    { id: 78, level: 4, children: [], name: ''},
    { id: 79, level: 4, children: [], name: ''},
    { id: 80, level: 4, children: [], name: ''},
    { id: 81, level: 4, children: [], name: ''},
    { id: 82, level: 4, children: [], name: ''},
    { id: 83, level: 4, children: [], name: ''},
    { id: 84, level: 4, children: [], name: ''},
    { id: 85, level: 4, children: [], name: ''},
    { id: 86, level: 4, children: [], name: ''},
    { id: 87, level: 4, children: [], name: ''},
    { id: 88, level: 4, children: [], name: ''},
    { id: 89, level: 4, children: [], name: ''},
    { id: 90, level: 4, children: [], name: ''},
    { id: 91, level: 4, children: [], name: ''},
    { id: 92, level: 4, children: [], name: ''},
    { id: 93, level: 4, children: [], name: ''},
    { id: 94, level: 4, children: [], name: ''},
    { id: 95, level: 4, children: [], name: ''},
    { id: 96, level: 4, children: [], name: ''},
    { id: 97, level: 4, children: [], name: ''},
    { id: 98, level: 4, children: [], name: ''},
    { id: 99, level: 4, children: [], name: ''},
    { id: 100, level: 4, children: [], name: ''},
    { id: 101, level: 4, children: [], name: ''},
    { id: 102, level: 4, children: [], name: ''},
    { id: 103, level: 4, children: [], name: ''},
    { id: 104, level: 4, children: [], name: ''},
    { id: 105, level: 4, children: [], name: ''},
    { id: 106, level: 4, children: [], name: ''},
    { id: 107, level: 4, children: [], name: ''},
    { id: 108, level: 4, children: [], name: ''},
    { id: 109, level: 4, children: [], name: ''},
    { id: 110, level: 4, children: [], name: ''},
    { id: 111, level: 4, children: [], name: ''},
    { id: 112, level: 4, children: [], name: ''},
    { id: 113, level: 4, children: [], name: ''},
    { id: 114, level: 4, children: [], name: ''},
    { id: 115, level: 4, children: [], name: ''},
    { id: 116, level: 4, children: [], name: ''},
    { id: 117, level: 4, children: [], name: ''},
    { id: 118, level: 4, children: [], name: ''},
    { id: 119, level: 4, children: [], name: ''},
    { id: 120, level: 4, children: [], name: ''},
    { id: 121, level: 4, children: [], name: ''},
    { id: 122, level: 4, children: [], name: ''},
    { id: 123, level: 4, children: [], name: ''},
    { id: 124, level: 4, children: [], name: ''},
    { id: 125, level: 4, children: [], name: ''},
    { id: 126, level: 4, children: [], name: ''},
    { id: 127, level: 4, children: [], name: ''},
    { id: 128, level: 4, children: [], name: ''},
    { id: 129, level: 4, children: [], name: ''},
    { id: 130, level: 4, children: [], name: ''},
    { id: 131, level: 4, children: [], name: ''},
    { id: 132, level: 4, children: [], name: ''},
    { id: 133, level: 4, children: [], name: ''},
    { id: 134, level: 4, children: [], name: ''},
    { id: 135, level: 4, children: [], name: ''},
    { id: 136, level: 4, children: [], name: ''},
    { id: 137, level: 4, children: [], name: ''},
    { id: 138, level: 4, children: [], name: ''},
    { id: 139, level: 4, children: [], name: ''},
    { id: 140, level: 4, children: [], name: ''},
    { id: 141, level: 4, children: [], name: ''},
    { id: 142, level: 4, children: [], name: ''},
    { id: 143, level: 4, children: [], name: ''},
    { id: 144, level: 4, children: [], name: ''},
    { id: 145, level: 4, children: [], name: ''},
    { id: 146, level: 4, children: [], name: ''},
    { id: 147, level: 4, children: [], name: ''},
    { id: 148, level: 4, children: [], name: ''},
    { id: 149, level: 4, children: [], name: ''},
    { id: 150, level: 4, children: [], name: ''},
    { id: 151, level: 4, children: [], name: ''},
    { id: 152, level: 4, children: [], name: ''},
    { id: 153, level: 4, children: [], name: ''},
    { id: 154, level: 4, children: [], name: ''},
    { id: 155, level: 4, children: [], name: ''},
    { id: 156, level: 4, children: [], name: ''},
    { id: 157, level: 4, children: [], name: ''},
    { id: 158, level: 4, children: [], name: ''},
    { id: 159, level: 4, children: [], name: ''},
    { id: 160, level: 4, children: [], name: ''},
    { id: 161, level: 4, children: [], name: ''},
    { id: 162, level: 4, children: [], name: ''},
    { id: 163, level: 4, children: [], name: ''},
    { id: 164, level: 4, children: [], name: ''},
    { id: 165, level: 4, children: [], name: ''},
    { id: 166, level: 4, children: [], name: ''},
    { id: 167, level: 4, children: [], name: ''},
    { id: 168, level: 4, children: [], name: ''},
    { id: 169, level: 4, children: [], name: ''},
    { id: 170, level: 4, children: [], name: ''},
    { id: 171, level: 4, children: [], name: ''},
    { id: 172, level: 4, children: [], name: ''},
    { id: 173, level: 4, children: [], name: ''},
    { id: 174, level: 4, children: [], name: ''},
    { id: 175, level: 4, children: [], name: ''},
    { id: 176, level: 4, children: [], name: ''},
    { id: 177, level: 4, children: [], name: ''},
    { id: 178, level: 4, children: [], name: ''},
    { id: 179, level: 4, children: [], name: ''},
    { id: 180, level: 4, children: [], name: ''},
    { id: 181, level: 4, children: [], name: ''},
    { id: 182, level: 4, children: [], name: ''},
    { id: 183, level: 4, children: [], name: ''},
    { id: 184, level: 4, children: [], name: ''},
    { id: 185, level: 4, children: [], name: ''},
    { id: 186, level: 4, children: [], name: ''},
    { id: 187, level: 4, children: [], name: ''},
    { id: 188, level: 4, children: [], name: ''},
    { id: 189, level: 4, children: [], name: ''},
    { id: 190, level: 4, children: [], name: ''},
    { id: 191, level: 4, children: [], name: ''},
    { id: 192, level: 4, children: [], name: ''},
    { id: 193, level: 4, children: [], name: ''},
    { id: 194, level: 4, children: [], name: ''},
    { id: 195, level: 4, children: [], name: ''},
    { id: 196, level: 4, children: [], name: ''},
    { id: 197, level: 4, children: [], name: ''},
    { id: 198, level: 4, children: [], name: ''},
    { id: 199, level: 4, children: [], name: ''},
    { id: 200, level: 4, children: [], name: ''},
    { id: 201, level: 4, children: [], name: ''},
    { id: 202, level: 4, children: [], name: ''},
    { id: 203, level: 4, children: [], name: ''},
    { id: 204, level: 4, children: [], name: ''},
    { id: 205, level: 4, children: [], name: ''},
    { id: 206, level: 4, children: [], name: ''},
    { id: 207, level: 4, children: [], name: ''},
    { id: 208, level: 4, children: [], name: ''},
    { id: 209, level: 4, children: [], name: ''},
    { id: 210, level: 4, children: [], name: ''},
    { id: 211, level: 4, children: [], name: ''},
    { id: 212, level: 4, children: [], name: ''},
    { id: 213, level: 4, children: [], name: ''},
    { id: 214, level: 4, children: [], name: ''},
    { id: 215, level: 4, children: [], name: ''},
    { id: 216, level: 4, children: [], name: ''},
    { id: 217, level: 4, children: [], name: ''},
    { id: 218, level: 4, children: [], name: ''},
    { id: 219, level: 4, children: [], name: ''},
    { id: 220, level: 4, children: [], name: ''},
    { id: 221, level: 4, children: [], name: ''},
    { id: 222, level: 4, children: [], name: ''},
    { id: 223, level: 4, children: [], name: ''},
    { id: 224, level: 4, children: [], name: ''},
    { id: 225, level: 4, children: [], name: ''},
    { id: 226, level: 4, children: [], name: ''},
    { id: 227, level: 4, children: [], name: ''},
    { id: 228, level: 4, children: [], name: ''},
    { id: 229, level: 4, children: [], name: ''},
    { id: 230, level: 4, children: [], name: ''},
    { id: 231, level: 4, children: [], name: ''},
    { id: 232, level: 4, children: [], name: ''},
    { id: 233, level: 4, children: [], name: ''},
    { id: 234, level: 4, children: [], name: ''},
    { id: 235, level: 4, children: [], name: ''},
    { id: 236, level: 4, children: [], name: ''},
    { id: 237, level: 4, children: [], name: ''},
    { id: 238, level: 4, children: [], name: ''},
    { id: 239, level: 4, children: [], name: ''},
    { id: 240, level: 4, children: [], name: ''},
    { id: 241, level: 4, children: [], name: ''},
    { id: 242, level: 4, children: [], name: ''},

]